# Generated by Django 3.2.5 on 2021-07-10 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=30)),
                ('status', models.TextField(default='อยู่')),
            ],
        ),
        migrations.CreateModel(
            name='TagHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2021, 7, 10, 12, 32, 58, 340491, tzinfo=utc))),
                ('image', models.ImageField(upload_to='images')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tag')),
            ],
        ),
    ]
